### ISSUE TITLE
Sexta práctica

### ISSUE THREAD

**Issue by jinchuika** [Csanchezz/practica#6]
# Problema

Generar un índice usando listas de HTML (`<li>`) en base al siguiente array:

``` php
$indice_detallado = array(
    array('nombre' => 'Introducción', 'num' => 3),
    array('nombre' => 'Descripción',   'num' => 5, 'subtemas' => array(
            array('nombre' => 'Funciones','num' => 6,
                'subtemas' => array(
                    array('nombre' => 'Funciones detalladas', 'num'=>8)
                    )
                ),
            array('nombre' => 'Actividades','num' => 9)
            )
        ),
    array('nombre' => 'Contenido','num' => 15,
        'subtemas' => array(
            array('nombre' => 'Interfaces', 'num' => 15),
            array('nombre' => 'Funciones específicas','num' => 15),
            array('nombre' => 'Atributos', 'num' => 20,
                'subtemas' => array(
                    array('nombre' => 'Propiedades generales', 'num' => 22),
                    array('nombre' => 'Propiedades únicas', 'num' => 24)
                    )
                ),
            array('nombre' => 'Consideraciones', 'num' => 26)
            )
        ),
    array('nombre' => 'Apéndices','num' => 27)
    );
```

El índice tiene subtemas, que deben aparecer como listas anidadas dentro de cada tema. El índice completo debe quedar de la siguiente manera:

> - Introducción ................... 3
> - Descripción ................... 5
>   - Funciones ................... 6
>     - Funciones detalladas ................... 8
>   - Actividades ................... 9
> - Contenido ................... 15
>   - Interfaces ................... 15
>   - Funciones específicas ................... 15
>   - Atributos ................... 20
>     - Propiedades generales ................... 22
>     - Propiedades únicas ................... 24
>   - Consideraciones ................... 26
> - Apéndices ................... 27
## Restricciones
- [x] El array `$indice_detallado` debe estar en un archivo llamado `config_detalle.php`, que esté en la misma carpeta en la que estaba el `config.php` de la práctica #5.
- [x] La función que genere el índice detallado debe estar en `controlador.php` de la práctica #5.
- [x] El índice generado debe poder ser accedido desde el mismo `index.php` de la práctica #5.
- [x] El archivo index.php debe recibir como parámetro el índice que se desea consultar. Si recibe como parámetro el índice _normal_, debe mostrar el de la práctica #5; si recibe como parámetro el índice _detallado_ debe mostrar el actual.
- [x] No es necesario crear los archivos para cada tema como se hizo en #5. Ahora basta con que los enlaces sean generados aunque no existan los archivos a los que conducen.

El ejercicio tendría la siguiente estructura de archivos:

```
práctica
├── config.php
├── config_detalle.php
├── controlador.php
├── index.php
└── contenido
    ├── 1.php
    ├── 2.php
    ├── 3.php
    ├── .....
    └── 12.php
```
## Objetivos
- Aprender a utilizar recursividad.

**Comment by jinchuika** [comment]
Para ver que funciona hasta el infinito, probá con este Array:

``` php
$indice = array(
    array('nombre' => 'Introducción', 'num' => 3),
    array('nombre' => 'Descripción',   'num' => 5, 'subtemas' => array(
            array('nombre' => 'Funciones','num' => 6,
                'subtemas' => array(
                    array('nombre' => 'Funciones detalladas', 'num'=>8,
                        'subtemas'=> array(
                            array('nombre'=>'algo', 'num'=>0,
                                'subtemas' => array(
                                    array('nombre'=> 'así', 'num' => 0,
                                        'subtemas'=> array(
                                            array('nombre'=>'como', 'num'=>0,
                                                'subtemas'=> array(
                                                    array('nombre'=>'esto', 'num'=>0,
                                                        'subtemas'=> array(
                                                            array('nombre'=>'xD', 'num'=>0)
                                                            ))
                                                    ))
                                            ))
                                    ))
                            ))
                    )
                ),
            array('nombre' => 'Actividades','num' => 9)
            )
        ),
    array('nombre' => 'Contenido','num' => 15,
        'subtemas' => array(
            array('nombre' => 'Interfaces', 'num' => 15),
            array('nombre' => 'Funciones específicas','num' => 15),
            array('nombre' => 'Atributos', 'num' => 20,
                'subtemas' => array(
                    array('nombre' => 'Propiedades generales', 'num' => 22),
                    array('nombre' => 'Propiedades únicas', 'num' => 24)
                    )
                ),
            array('nombre' => 'Consideraciones', 'num' => 26)
            )
        ),
    array('nombre' => 'Apéndices','num' => 27)
    );
```

Jejeje

**Comment by Csanchezz** [comment]
echo "hecho!"; /_hahahahahaha_/
